### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by kaaetech** [iilunin/crypto-bot#5]
2018-12-30 13:54:53,298[INFO][ExitStrategy(ONTBTC)|Binance WebSocket Thread]: Setting StopLoss-SELL for 0.00015935 - 2% of current Price: 0.00016020
2018-12-30 13:54:53,588[ERROR][ExitStrategy(ONTBTC)|Binance WebSocket Thread]: Traceback (most recent call last):
  File "/usr/src/app/Bot/Strategy/EntryStrategy.py", line 83, in execute
    self.handle_smart_target(trigger_order_price, price)
  File "/usr/src/app/Bot/Strategy/EntryStrategy.py", line 105, in handle_smart_target
    self.handle_stoploss_order(trigger_order_price, current_price)
  File "/usr/src/app/Bot/Strategy/EntryStrategy.py", line 183, in handle_stoploss_order
    volume=self.exchange_info.adjust_quanity(vol)
  File "/usr/src/app/Bot/FXConnector.py", line 151, in create_stop_order
    price=FXConnector.format_number(price))
  File "/usr/local/lib/python3.6/site-packages/binance/client.py", line 1133, in create_order
    return self._post('order', True, data=params)
  File "/usr/local/lib/python3.6/site-packages/binance/client.py", line 209, in _post
    return self._request_api('post', path, signed, version, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/binance/client.py", line 180, in _request_api
    return self._request(method, uri, signed, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/binance/client.py", line 175, in _request
    return self._handle_response(response)
  File "/usr/local/lib/python3.6/site-packages/binance/client.py", line 199, in _handle_response
    raise BinanceAPIException(response)
binance.exceptions.BinanceAPIException: APIError(code=-1013): Invalid price.

Error -1013 
https://www.reddit.com/r/binance/comments/7ej5cn/api_error_code1013_filter_falinure_price_filter/ seems to be something to do with wrong amount. Selling "10.153" ONT wont work while "10.15" will.

**Comment by kaaetech** [comment]
It had to with my trading file. I needed 7 decimals over 8.
